spring.application.name=TrainScheduler

spring.data.mongodb.uri=mongodb+srv://trainUser:trainPass123@cluster0.zsw04h9.mongodb.net/trainDB?retryWrites=true&w=majority&appName=Cluster0



# Logging
spring.data.mongodb.logging.level=INFO

# Optional: H2 console disabled
spring.h2.console.enabled=false
spring.main.allow-bean-definition-overriding=true